name = "bluehawana-portfolio"
compatibility_date = "2026-01-01"

[build]
command = ""

[pages]
# Directory containing static assets to deploy
pages_build_output_dir = "cf-deploy"

[vars]
ACCOUNT_ID = "2a35af424f8734e497a5d707344d79d5"