name = "bluehawana-portfolio"
main = "workers-site/index.js"
compatibility_date = "2026-01-01"
workers_dev = true

[site]
bucket = "./"
entry-point = "workers-site"

[build]
command = ""
watch_dir = ""

[vars]
ACCOUNT_ID = "2a35af424f8734e497a5d707344d79d5"